from enum import StrEnum


class EstadoEnum(StrEnum):
    ACRE = "AC"
    ALAGOAS = "AL"
    AMAZONAS = "AM"
    AMAPA = "AP"
    BHAIA = "BA"
    CEARA = "CE"
    DISTRIDO_FEDERAL = "DF"
    ESPIRITO_SANTO = "ES"
    GOIAS = "GO"
    MARANHAO = "MA"
    MATO_GROSSO = "MT"
    MATO_GRASSO_DO_SUL = "MS"
    MINAS_GERAIS = "MG"
    PARA = "PA"
    PARAIBA = "PB"
    PARANA = "PR"
    PERNAMBUCO = "PE"
    PIAUI = "PI"
    RIO_DE_JANEIRO = "RJ"
    RIO_GRANDE_DO_NORTE = "RN"
    RIO_GRANDE_DO_SUL = "RS"
    RONDONIA = "RO"
    RORAIMA = "RR"
    SANTA_CATARINA = "SC"
    SAO_PAULO = "SP"
    SERGIPE = "SE"
    TOCANTINS = "TO"
    # Internacionais
    ARGENTINA = "AR"
    BOLIVIA = "BO"
    CHILE = "CH"
    COLOMBIA = "CO"
    EQUADOR = "EQ"
    GUIANA_FRANCESA = "GF"
    GUIANA = "GU"
    PARAGUAI = "PG"
    PERU = "PU"
    SURINAME = "SU"
    URUGUAI = "UR"
    VENEZUELA = "VE"
