from api_hidro.async_requests.models import Inventario


def test_inventario_model_simple_validation():
    sample = {
        "altitude": None,
        "area_drenagem": None,
        "bacia_nome": "Bacia",
        "codigo_adicional": None,
        "codigo_operadora_unidade_uf": None,
        "data_periodo_climatologica_fim": None,
        "data_periodo_climatologica_inicio": None,
        "data_periodo_desc_liquida_fim": None,
        "data_periodo_desc_liquida_inicio": None,
        "data_periodo_escala_fim": None,
        "data_periodo_escala_inicio": None,
        "data_periodo_piezometria_fim": None,
        "data_periodo_piezometria_inicio": None,
        "data_periodo_pluviometro_fim": None,
        "data_periodo_pluviometro_inicio": None,
        "data_periodo_qual_agua_fim": None,
        "data_periodo_qual_agua_inicio": None,
        "data_periodo_registrador_chuva_fim": None,
        "data_periodo_registrador_chuva_inicio": None,
        "data_periodo_registrador_nivel_fim": None,
        "data_periodo_registrador_nivel_inicio": None,
        "data_periodo_sedimento_inicio": None,
        "data_periodo_sedimento_fim": None,
        "data_periodo_tanque_evapo_fim": None,
        "data_periodo_tanque_evapo_inicio": None,
        "data_periodo_telemetrica_fim": None,
        "data_periodo_telemetrica_inicio": None,
        "data_ultima_atualizacao": None,
        "estacao_nome": "Estacao",
        "latitude": 0.0,
        "longitude": 0.0,
        "municipio_codigo": 1,
        "municipio_nome": "Mun",
        "operadora_codigo": 1,
        "operadora_sigla": 1,
        "operadora_sub_unidade_uf": None,
        "operando": True,
        "responsavel_codigo": 1,
        "responsavel_sigla": "R",
        "responsavel_unidade_uf": 1,
        "rio_codigo": None,
        "rio_nome": "Rio",
        "sub_bacia_codigo": 1,
        "sub_bacia_nome": "Sub",
        "tipo_estacao": "pluviometrica",
        "tipo_estacao_climatologica": False,
        "tipo_estacao_desc_liquida": False,
        "tipo_estacao_escala": False,
        "tipo_estacao_piezometria": False,
        "tipo_estacao_pluviometro": False,
        "tipo_estacao_qual_agua": False,
        "tipo_estacao_registrador_chuva": False,
        "tipo_estacao_registrador_nivel": False,
        "tipo_estacao_sedimentos": False,
        "tipo_estacao_tanque_evapo": False,
        "tipo_estacao_telemetrica": False,
        "tipo_rede_basica": False,
        "tipo_rede_captacao": False,
        "tipo_rede_classe_vazao": False,
        "tipo_rede_curso_dagua": False,
        "tipo_rede_energetica": False,
        "tipo_rede_estrategica": False,
        "tipo_rede_navegacao": False,
        "tipo_rede_qual_agua": False,
        "tipo_rede_sedimentos": False,
        "uf_estacao": "AC",
        "uf_nome_estacao": "AC",
        "codigobacia": 1,
        "codigoestacao": 42,
    }

    inv = Inventario.model_validate(sample)
    assert inv.codigoestacao == 42
    assert inv.bacia_nome == "Bacia"
    assert isinstance(inv.estacao_nome, str)
    assert inv.latitude == 0.0
